#!/bin/sh -eux

autoreconf -vif

echo mount-archive.desktop.in >> po/POTFILES.in
echo mount-archive.desktop.in.in >> po/POTFILES.in

ub_compile \
	--disable-bash-completion \
	--disable-hal \
	--enable-archive \
	--enable-avahi \
	--enable-bluray \
	--enable-cdda \
	--enable-fuse \
	--enable-gdu \
	--enable-gphoto2
