#!/bin/sh -eux

mkdir -p ${UB_INSTALLDIR}/usr/share/doc/bsfilter/examples/

cp -a ${UB_COMPILEDIR}/bsfilter/bsfilter ${UB_INSTALLDIR}/usr/bin
cp -a ${UB_COMPILEDIR}/mda/ ${UB_INSTALLDIR}/usr/share/doc/bsfilter/examples/
cp -a ${UB_COMPILEDIR}/mua/ ${UB_INSTALLDIR}/usr/share/doc/bsfilter/examples/

