#!/bin/sh -eux

cd "$UB_OBJECTDIR"

OPT_FLAGS="-O2 -mtune=generic"

CFLAGS="$OPT_FLAGS" \
CXXFLAGS="$OPT_FLAGS" \
XCFLAGS="$OPT_FLAGS" \
TCFLAGS="$OPT_FLAGS" \
GCJFLAGS="$OPT_FLAGS" \
"$UB_COMPILEDIR"/configure \
	--prefix=/usr \
	--infodir=/usr/share/info \
	--mandir=/usr/share/man \
	--enable-languages=java \
	--enable-shared \
	--with-gnu-as \
	--with-gnu-ld \
	--with-system-zlib \
	--build=i686-uhu-linux \
	--host=i686-uhu-linux \
	--target=i686-uhu-linux \
	--enable-targets=all \
	--with-arch-32=i686 \
	--with-arch-64=core2 \
	--with-cpu-32=i686 \
	--with-cpu-64=core2 \
	--disable-multilib \
	--with-tune=generic

ub_make -j4
