#!/bin/sh -eux

cd "$UB_OBJECTDIR"

make \
	prefix="$UB_INSTALLDIR"/usr \
	infodir="$UB_INSTALLDIR"/usr/share/info \
	mandir="$UB_INSTALLDIR"/usr/share/man \
	install

for i in $(dpkg -L cpp gcc gcc-lib libstdc++ libstdc++-dev); do
	rm "$UB_INSTALLDIR/$i" 2>/dev/null || true
done

# remove conflicting files
rm "$UB_INSTALLDIR"/usr/lib/libffi.*
