#!/bin/sh -eux

ub_install
install -D -m644 sample.fvwmrc/{decor_examples,DecorMwm,DecorWin95,new-features,system.*} \
	"${UB_INSTALLDIR}/usr/share/doc/fvwm"
mkdir -p "${UB_INSTALLDIR}"/etc
cp sample.fvwmrc/system.fvwm2rc "${UB_INSTALLDIR}"/etc/
