#!/bin/sh -eux

ub_compile \
	--enable-bz2 \
	--enable-zlib \
	--enable-experimental \
	--disable-examples \
	--with-default-audiosink=autoaudiosink \
	--with-default-visualizer=goom \
	--disable-hal
