#!/bin/sh -eux

ub_install
testdir=$UB_INSTALLDIR/usr/share/dvb/
mkdir -p $testdir
rm test/{*.c,*.o,*.d,*.h,Makefile}
rm test/{libucsi/,libesg/,libdvben50221/,libdvbcfg/}{*.c,*.d,Makefile}
rm test/libdvbsec/{*.c,Makefile}
mv test $testdir/
