#!/bin/sh -eux

ub_compile \
	--with-avahi-priv-access-group=avahi \
	--with-autoipd-user=avahi \
	--with-autoipd-group=avahi \
	--with-distro=none \
	--enable-compat-libdns_sd \
	--enable-compat-howl \
	--enable-mono \
	--disable-qt3 \
	--disable-qt4
