#!/bin/sh -eux

cd Python
ub_install

# remove conflicting files with qscintilla2-python
rm "$UB_INSTALLDIR"/usr/share/sip/PyQt4/Qsci/*.sip
rm -Rf "$UB_INSTALLDIR"/usr/lib/qt4/api/python

mkdir -p "$UB_INSTALLDIR"/usr/lib/qt4/qsci/api/python
cp ../qsci/api/python/Python-3*.api "$UB_INSTALLDIR"/usr/lib/qt4/qsci/api/python
