#!/bin/sh -eux

make INSTALL_ROOT="$UB_INSTALLDIR" install

# a desktop fájlok kedvéért szimlinkelünk az /usr/bin-be

ln -s ../lib/qt5/bin/assistant "$UB_INSTALLDIR"/usr/bin/assistant-qt5
ln -s ../lib/qt5/bin/designer "$UB_INSTALLDIR"/usr/bin/designer-qt5
ln -s ../lib/qt5/bin/linguist "$UB_INSTALLDIR"/usr/bin/linguist-qt5
ln -s ../lib/qt5/bin/lrelease "$UB_INSTALLDIR"/usr/bin/lrelease-qt5
ln -s ../lib/qt5/bin/lupdate "$UB_INSTALLDIR"/usr/bin/lupdate-qt5
ln -s ../lib/qt5/bin/moc "$UB_INSTALLDIR"/usr/bin/moc-qt5
ln -s ../lib/qt5/bin/uic "$UB_INSTALLDIR"/usr/bin/uic-qt5
ln -s ../lib/qt5/bin/qdbus "$UB_INSTALLDIR"/usr/bin/qdbus-qt5
ln -s ../lib/qt5/bin/qdbusviewer "$UB_INSTALLDIR"/usr/bin/qdbusviewer-qt5
ln -s ../lib/qt5/bin/qmake "$UB_INSTALLDIR"/usr/bin/qmake-qt5

# pkgconfig linkek
mkdir -p "$UB_INSTALLDIR"/usr/lib/pkgconfig
for pc in "$UB_INSTALLDIR"/usr/lib/qt5/lib/pkgconfig/*.pc; do
	ln -s ../../lib/qt5/lib/pkgconfig/`basename $pc` "$UB_INSTALLDIR"/usr/lib/pkgconfig/`basename $pc`
done
