#!/bin/sh -eux

export SHELL=/bin/bash
export LDFLAGS="-Wl,-rpath,/usr/lib/seamonkey/ -Wl,--no-keep-memory"

cd "$UB_OBJECTDIR"
mkdir -p mozilla/js/src/.deps

# az UB_CONFIGURE_DIR="$UB_COMPILEDIR" forma nem jó, linker hiba lesz belőle
# a configure opcióknak a 2.26-nál a .mozconfig fájlban kell lenniük, különben
# hibára fut

"$UB_COMPILEDIR"/configure
	
ub_make

