#!/bin/sh -eux

install -Dm755 build/libfreshwrapper-pepperflash.so "$UB_INSTALLDIR"/usr/lib/firefox/plugins/libfreshwrapper-pepperflash.so

install -Dm644 data/freshwrapper.conf.example \
    "$UB_INSTALLDIR"/usr/share/freshplayerplugin/freshwrapper.conf.example
    
install -Dm644 data/freshwrapper.conf.example "$UB_INSTALLDIR"/etc/freshwrapper.conf
