#!/bin/sh -eux

export PERL_MM_USE_DEFAULT=1 PERL5LIB="" \
  PERL_AUTOINSTALL=--skipdeps \
  PERL_MM_OPT="INSTALLDIRS=vendor DESTDIR='$UB_INSTALLDIR'" \
  PERL_MB_OPT="--installdirs vendor --destdir '$UB_INSTALLDIR'" \
  MODULEBUILDRC=/dev/null
perl Makefile.PL
make
export PERL_MM_USE_DEFAULT=1 PERL5LIB=""
make test
