#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/share/freemind
mkdir -p "$UB_INSTALLDIR"/etc/freemind
chmod 755 freemind.sh
cp -a . "$UB_INSTALLDIR"/usr/share/freemind/
cp -a patterns.xml "$UB_INSTALLDIR"/etc/freemind/
