#!/bin/sh -eux

# old glib
sed -i -e "s/2.36.0/2.34.0/g" configure

# with-cpufreq-lib=cpupower

ub_compile \
	--with-gtk=2.0 \
	--libexecdir=/usr/libexec/mate \
	--with-cpufreq-lib=cpufreq \
	--without-hal
