#!/bin/sh -eux

ub_install

# check shipped .fdi for correctness, otherwise hald silently fails...
find "$UB_INSTALLDIR"/etc/hal/fdi -name "*.fdi" -type f | while read f; do
	xmllint --noout --dtdvalid "$UB_INSTALLDIR"/etc/hal/fdi/fdi.dtd "$f"
done

cp -a hal{,-storage}.pc "$UB_INSTALLDIR"/usr/lib/pkgconfig
mv "$UB_INSTALLDIR"/usr/lib/udev "$UB_INSTALLDIR"/lib
#rm "$UB_INSTALLDIR"/usr/libexec/hal-storage-{un,}mount
