#!/bin/sh -eux
cp build/bin/paintown ./
mkdir -p $UB_INSTALLDIR/usr/{bin,share/{games/paintown,pixmaps,applications,licenses/paintown}}
sh install.sh -d $UB_INSTALLDIR/usr/share/games/paintown -b $UB_INSTALLDIR/usr/bin
sed -i "s#$UB_INSTALLDIR##g" $UB_INSTALLDIR/usr/bin/paintown
