#!/bin/sh -eux

export FC=gfortran

pushd BLAS/SRC
make clean
FFLAGS="-O0" make dcabs1.o
FFLAGS="-fPIC" CFLAGS="-fPIC" make shared
cp libblas.so.* ../../
popd
ln -s libblas.so.* libblas.so
              
pushd INSTALL
make clean
make NOOPT="-O0 -fPIC" OPTS="-fPIC"
popd

pushd SRC
make clean
make FFLAGS="-fPIC" CFLAGS="-fPIC" shared
cp liblapack.so.* ../
popd
