#!/bin/sh -eux

ub_install

rm $UB_INSTALLDIR//usr/lib/python2.6/site-packages/*.la
rm $UB_INSTALLDIR//usr/lib/python2.6/site-packages/blueman/plugins/config/Gconf.py
rm $UB_INSTALLDIR//usr/lib/python2.6/site-packages/blueman/{main/Pulse*.py,plugins/applet/Pulse*.py}
