#!/bin/sh -eux

cp -R usr ${UB_INSTALLDIR}
mkdir -p ${UB_INSTALLDIR}/usr/lib/linuxmint/common
cat > ${UB_INSTALLDIR}/usr/lib/linuxmint/common/version.py << "EOF"
#!/usr/bin/python

import apt
import sys

try:
	cache = apt.Cache()	
	pkg = cache[sys.argv[1]]
	if pkg.installed is not None:
		print pkg.installed.version
	else:
		print ""
except:
	print ""

EOF
chmod +x ${UB_INSTALLDIR}/usr/lib/linuxmint/common/version.py
