#!/bin/sh -eux
install -m 755 rocksndiamonds $UB_INSTALLDIR/usr/bin/
install -d -m 755 $UB_INSTALLDIR/usr/share/games/rocksndiamonds
install -d -m 777 $UB_INSTALLDIR/var/games/rocksndiamonds/scores
cp -r docs graphics levels music sounds $UB_INSTALLDIR/usr/share/games/rocksndiamonds/
install -m 644 rocksndiamonds.1 $UB_INSTALLDIR/usr/share/man/man1/
