#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/lib/projectlibre

cp projectlibre.sh "$UB_INSTALLDIR"/usr/bin/projectlibre
cp projectlibre.jar "$UB_INSTALLDIR"/usr/lib/projectlibre/
cp -r lib "$UB_INSTALLDIR"/usr/lib/projectlibre/
