#!/bin/sh -eux

./configure \
	--prefix-dir=/usr \
	--binary-dir=bin \
	--data-dir=share/games/openttd \
	--icon-dir=share/pixmaps \
	--doc-dir=share/doc/Packages/openttd \
	--personal-dir=.openttd \
	--install-dir="$UB_INSTALLDIR" \
	--menu-group="Game;X-UHU-Menu/Games/TacticStrategy;"

ub_make
