#!/bin/sh -eux

ub_install

## shipped by icon-theme-hicolor
rm -f "$UB_INSTALLDIR"/usr/share/icons/hicolor/index.theme

ln -s /usr/lib/kde4/libexec/kdesu "$UB_INSTALLDIR"/usr/bin
rm -f "$UB_INSTALLDIR"/usr/share/man/man1/plasmapkg.1
