#!/bin/sh -eux

ub_compile \
	--enable-conduits \
	--enable-threads \
	--enable-libusb \
	--with-perl=yes \
	--with-libiconv=yes \
	--with-java=/usr/lib/java \
	--with-python=yes \
	--with-tcl=/usr/lib
