#!/bin/sh -eux

mv depend.mk "$UB_WORKDIR"/compile/autoconf/make/depend.mk~
mv filelist.mk "$UB_WORKDIR"/compile/autoconf/make/filelist.mk~
mv modules.mk "$UB_WORKDIR"/compile/autoconf/make/modules.mk~
ub_compile \
--prefix=/usr \
--mandir=/usr/share/man
