#!/bin/sh -eux

aclocal
automake --add-missing
intltoolize --force --copy --automake
autoreconf
ub_compile \
	--disable-examples \
	--disable-static \
	--enable-polkit \
	--disable-volume-search \
	--enable-gusb \
	--with-daemon-user=colord
