#!/bin/sh -eux

ub_install
mv "$UB_INSTALLDIR"/usr/share/applications/kde/kbarcode{,-batch,-editor,-label,-single}.desktop \
	"$UB_INSTALLDIR"/usr/share/applications/

rmdir "$UB_INSTALLDIR"/usr/share/applications/kde
