#!/bin/sh -eux

export QTDIR=/usr/lib/qt
cmake \
	-DCMAKE_INSTALL_PREFIX:PATH="$UB_INSTALLDIR"/usr \
	-DDEFAULT_DATA_DIR=/usr/share/canorus \
	-DQT_QMAKE_EXECUTABLE=/usr/lib/qt4/bin/qmake \
	.
ub_make
