#!/bin/sh -eux

ub_compile \
	--with-screen=ncurses \
	--enable-vfs       \
	--enable-vfs-undelfs \
	--enable-vfs-smb \
	--enable-charset

cd po
	rm *.gmo
	for i in *.po; do
		make "${i/.po/.gmo}"
	done
cd ..
