diff -urN dhex_0.55.orig/Makefile dhex_0.55/Makefile
--- dhex_0.55.orig/Makefile	2004-03-17 00:00:23.000000000 +0100
+++ dhex_0.55/Makefile	2009-05-25 15:00:21.000000000 +0200
@@ -1,7 +1,7 @@
 CC=gcc
-#CFLAGS=-DLINUX=1 -O3 -Wall -I/homes/tdettbar/local/include
+CFLAGS=-DLINUX=1 -O3 -Wall -I/homes/tdettbar/local/include
 #CFLAGS=-DHPUX=1 -O3 -Wall -I/homes/tdettbar/local/include
-CFLAGS=-DFREEBSD=1 -O3 -Wall -I/homes/tdettbar/local/include
+#CFLAGS=-DFREEBSD=1 -O3 -Wall -I/homes/tdettbar/local/include
 #CFLAGS=-DSOLARIS=1 -O3 -Wall -I/homes/tdettbar/local/include
 #CFLAGS=-DIRIX=1 -O3 -Wall -I/homes/tdettbar/local/include
 LDFLAGS=-L/homes/tdettbar/local/lib
