#!/bin/sh -eux

ub_install
find "$UB_INSTALLDIR"/usr/share/themes -name ICON.png -size 0 | xargs -r rm
# a gtk3 témák max. a gtk3 3.2-ig használhatók
find "$UB_INSTALLDIR"/usr/share/themes -type d -name 'gtk-3.0' | xargs -r rm -Rf