#!/bin/sh -eux
CFLAGS="-O2 -march=i686 -mtune=generic -fomit-frame-pointer -I/usr/include/directfb" \
./configure \
	--extra-cflags="-DHAVE_ISNAN -DHAVE_ISINF" \
	--prefix=/usr \
	--datadir=/usr/share/mplayer \
	--confdir=/etc/mplayer \
	--codecsdir=/usr/lib/codecs \
	--enable-mencoder \
	--disable-termcap \
	--enable-runtime-cpudetection \
	--language="hu bg cs de dk el en es fr it ja ko mk nb nl pl ro ru sk sv tr uk pt_BR zh_CN zh_TW" \
	--enable-gui \
	--enable-menu \
	--disable-fribidi \
	--enable-bl \
	--enable-xvmc \
	--enable-mga \
	--enable-xmga \
	--enable-vdpau \
	--disable-libdvdcss-internal \
	--disable-dvdread-internal \
	--enable-libopenjpeg \
	--enable-libgsm \
	--enable-radio \
	--enable-radio-capture \
	--enable-directfb

ub_make
