#!/bin/sh -eux

ub_install

# no need for and it depends on perl
#rm "$UB_INSTALLDIR"/usr/bin/chkdupexe

# remove execute bit from these examples, we dont want to depend on tcsh
chmod -x "$UB_INSTALLDIR"/usr/share/getopt/*
