#!/bin/sh -eux

#mkdir -p "$UB_INSTALLDIR"/usr/lib/chessx/bin
#mkdir -p "$UB_INSTALLDIR"/usr/lib/chessx/data
#cp -a {bin,data} "$UB_INSTALLDIR"/usr/lib/chessx/
install -Dm755 release/chessx $UB_INSTALLDIR/usr/bin/chessx
mkdir -p "$UB_INSTALLDIR"/usr/share/pixmaps
install -Dm644 data/images/chessx.png $UB_INSTALLDIR/usr/share/pixmaps/chessx.png
install -Dm644 unix/chessx.desktop $UB_INSTALLDIR/usr/share/applications/chessx.desktop
