#!/bin/sh -eux
dataroot="$UB_INSTALLDIR"/usr/share/games/arkanoidsb
mkdir -p $dataroot
cp -R * "$dataroot"/
rm "$dataroot"/README #hogy ne legyen két helyen
chmod +rx "$dataroot"/{*,res/*}
mkdir -p "$UB_INSTALLDIR"/usr/share/pixmaps
ln -s /usr/share/games/arkanoidsb/arkanoidsb.png "$UB_INSTALLDIR"/usr/share/pixmaps/arkianoidsb.png
