diff -Naurd a/Makefile b/Makefile
--- a/Makefile	1970-01-01 01:00:00.000000000 +0100
+++ b/Makefile	2004-09-09 06:21:07.000000000 +0200
@@ -0,0 +1,39 @@
+BINDIR = /usr/bin
+DESTDIR = ..overridden in spec file..
+
+all: install
+
+install: install-xsl install-img install-extensions install-misc
+
+install-xsl:
+	mkdir -p $(DESTDIR)/{common,fo,html,htmlhelp/doc,javahelp,lib,template,xhtml,manpages,profiling}
+	cp common/*.dtd $(DESTDIR)/common
+	cp common/*.xml $(DESTDIR)/common
+	cp common/*.xsl $(DESTDIR)/common
+	cp fo/*.xml $(DESTDIR)/fo
+	cp fo/*.xsl $(DESTDIR)/fo
+	cp html/*.xml $(DESTDIR)/html
+	cp html/*.xsl $(DESTDIR)/html
+	cp htmlhelp/*.xsl $(DESTDIR)/htmlhelp
+	cp javahelp/*.xsl $(DESTDIR)/javahelp
+	cp lib/lib.xsl $(DESTDIR)/lib
+	cp template/README $(DESTDIR)/template
+	cp template/*.xml $(DESTDIR)/template
+	cp template/*.xsl $(DESTDIR)/template
+	cp xhtml/*.xsl $(DESTDIR)/xhtml
+	cp manpages/README $(DESTDIR)/manpages
+	cp manpages/*.xsl $(DESTDIR)/manpages
+	cp profiling/*.xsl $(DESTDIR)/profiling
+
+install-img:
+	mkdir -p $(DESTDIR)/images/callouts
+	cp images/*.gif $(DESTDIR)/images
+	cp images/*.png $(DESTDIR)/images
+	cp images/callouts/*.png $(DESTDIR)/images/callouts
+
+install-extensions:
+	mkdir -p $(DESTDIR)/extensions
+	cp -r extensions/* $(DESTDIR)/extensions
+
+install-misc:
+	cp VERSION $(DESTDIR)
