#!/bin/sh -eux

# ub_install
python3 setup.py install --root="$UB_INSTALLDIR"

pythonpath="$UB_INSTALLDIR"/usr/lib/python3.3/site-packages
sed -i "s,$UB_INSTALLDIR,,g" "$pythonpath/gramps/gen/utils/resource-path"
