#!/bin/sh -eux

mkdir -p js/src/.deps

export SHELL=/bin/bash
export LDFLAGS="-Wl,-rpath,/usr/lib/xulrunner/"

ub_compile \
	--with-system-bz2 \
	--with-system-nspr \
	--with-system-nss \
	--with-system-zlib \
	--with-pthreads \
	--enable-application=xulrunner \
	--enable-canvas \
	--enable-default-toolkit=cairo-gtk2 \
	--enable-extensions=default \
	--enable-gio \
	--enable-libnotify \
	--enable-pango \
	--enable-safe-browsing \
	--enable-shared-js \
	--enable-startup-notification \
	--enable-svg \
	--enable-system-cairo \
	--enable-system-hunspell \
	--enable-system-lcms \
	--enable-system-sqlite \
	--enable-url-classifier \
	--enable-xinerama \
	--disable-cpp-exceptions \
	--disable-crashreporter \
	--disable-debug \
	--disable-gnomeui \
	--disable-gnomevfs \
	--disable-installer \
	--disable-javaxpcom \
	--disable-mochitest \
	--disable-necko-wifi \
	--disable-tests

