#!/bin/sh -eux
cd ros
ub_install
cd ..
mkdir -p "$UB_INSTALLDIR"/usr/share/doc/opencascade/examples
cp -r doc/{overview,ReferenceDocumentation} "$UB_INSTALLDIR"/usr/share/doc/opencascade/
cp -r {samples,data} "$UB_INSTALLDIR"/usr/share/doc/opencascade/examples
