#!/bin/sh -eux
cp $UB_SRCDIR/patches/menu.c.skip menu.c

make	CONFDIR=/var/vdr/config \
	VIDEODIR=/var/vdr/video \
	DVBDIR=/usr/include/linux/dvb
	INCLUDES="-I/usr/include/vdr -I/usr/include/linux/dvb"
