#!/bin/sh -eux

#	EXTRAS+=extras/{{ata,cdrom,dasd,edd,path,scsi,usb,volume}_id,firmware,floppy,rule_generator} \
ub_compile \
	--libexecdir=/lib/udev \
	--exec-prefix= \
	USE_KLIBC=false \
	USE_LOG=true \
	DEBUG=false
