#!/bin/sh -eux

autoreconf -vif

# GData:
# http://www.thewildbeast.co.uk/claws-mail/bugzilla/show_bug.cgi?id=3432

ub_compile \
    --enable-crash-dialog \
    --disable-gtk3 \
    --disable-ldap \
    --disable-jpilot \
    --disable-gdata-plugin
