#!/bin/sh -eux

ub_compile \
	--enable-gstreamer \
	--enable-alsa \
	--enable-usb \
	--enable-tools \
	--enable-bccmd \
	--enable-hid2hci \
	--enable-dfutool \
	--enable-hidd \
	--enable-pand \
	--enable-dund \
	--enable-cups \
	--enable-test \
	--enable-pcmcia
