#!/bin/sh -eux

ub_install

# fix .pc file
sed -i 's/ -L / /g' "$UB_INSTALLDIR"/usr/lib/pkgconfig/gnokii.pc
sed -i 's/ -L / /g' "$UB_INSTALLDIR"/usr/lib/pkgconfig/xgnokii.pc

cp -a Docs/sample/gnokiirc "$UB_INSTALLDIR"/etc/
