#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/share/gambas3/icons
mkdir -p "$UB_INSTALLDIR"/usr/share/applications
mkdir -p "$UB_INSTALLDIR"/usr/share/pixmaps
	
ub_install
cp app/desktop/gambas3.desktop "$UB_INSTALLDIR"/usr/share/applications
cp app/desktop/gambas3.png "$UB_INSTALLDIR"/usr/share/pixmaps