#!/bin/sh -eux

gemdir="$(ruby -rubygems -e 'puts Gem::dir')"

gem install --local --install-dir="$UB_INSTALLDIR/$gemdir" rake-"$UB_VERSION".gem

mv "$UB_INSTALLDIR/$gemdir"/bin/rake "$UB_INSTALLDIR"/usr/bin/
