#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/include/colibri
ub_install
cp -a colibri/. "$UB_INSTALLDIR"/usr/include/colibri/
ln -s ./colibri/colibri.h "$UB_INSTALLDIR"/usr/include/colibri.h
cp -a docu/. "$UB_INSTALLDIR"/usr/share/colibri/

mv "$UB_INSTALLDIR"/usr/bin/mini "$UB_INSTALLDIR"/usr/share/colibri/
cp -a mini/*.colibri "$UB_INSTALLDIR"/usr/share/colibri/
