#!/bin/sh -eux

sed -e "s:/usr/lib/gnome-session/gnome-session-check-accelerated:/usr/libexec/gnome-session-check-accelerated:" \
	-i "files/usr/share/gnome-session/sessions/cinnamon.session"

ub_compile \
	--enable-compile-warnings=maximum \
	--disable-jhbuild-wrapper-script \
	--with-ca-certificates=/usr/lib/certs/ca-certificates.crt \
		BROWSER_PLUGIN_DIR=/usr/lib/nsbrowser/plugins
