#!/bin/sh -eux
#cp $UB_SRCDIR/patches/gnome-autogen.sh.skip gnome-autogen.sh
#chmod +x gnome-autogen.sh
#./autogen.sh
sed -i '/AM_MAINTAINER/d' configure.ac
# „config.status: error: po/Makefile.in.in was not created by intltoolize.” miatt
sed -i '/AM_GNU_GETTEXT/d' configure.ac
ub_compile \
	--enable-compile-warnings=maximum \
	--disable-jhbuild-wrapper-script \
	--with-ca-certificates=/usr/lib/certs/ca-certificates.crt \
		BROWSER_PLUGIN_DIR=/usr/lib/nsbrowser/plugins
