#!/bin/bash -eux

#előkészület
KVER="$(ls -1 /lib/modules|grep i386)"
forras="NVIDIA-Linux-x86-${UB_VERSION}-pkg0"
moduldir="$UB_COMPILEDIR/lib/modules/"$KVER"/kernel/drivers"
mkdir -p $moduldir
#kicsomagolás és belépés
unmakeself $forras.run
rm $forras.run
cd usr/share/applications
patch -i "$UB_SRCDIR"/patches/menu.patch.skip
cd ../../src/nv
ln -s Makefile.kbuild Makefile
make SYSSRC=/usr/src/linux KERNEL_UNAME="$KVER" MODULE_ROOT=$moduldir module
#akdályok leküzdése a telepítéshez
sed -e 's/suser-sanity-check //g' -i Makefile.kbuild
sed -e 's/depmod -ae/true/g' -i Makefile.kbuild
#elkészült modul telepítése
make SYSSRC=/usr/src/linux KERNEL_UNAME="$KVER" MODULE_ROOT=$moduldir module-install
#ez minek? De legyen..
make clean
