#!/bin/sh -eux
for i in\
	wolf3d-shareware-v11\
	wolf3d-shareware-v12\
	wolf3d-shareware-v14\
	wolf3d-full-apogee-v11\
	wolf3d-full-gt-id-activision-v14\
	spear-demo\
	spear-full
do
#illető könyvtár
install -d -m 777 "$UB_INSTALLDIR"/usr/share/games/wolf4sdl/"$i"
#illető bináris
install -m 755 "$i".bin "$UB_INSTALLDIR"/usr/share/games/wolf4sdl/"$i"/wolf4sdl
done
