#!/bin/sh -eux

#datarootdir=/usr/share/games/xgalaga-sdl ub_compile
	CFLAGS='-O2 -march=i686 -mtune=generic' \
./configure \
	--prefix=/usr \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--mandir=/usr/share/man  \
	--infodir=/usr/share/info  \
	--datarootdir=/usr/share/games/xgalaga-sdl

