[Desktop Entry]
Name=Sonar
Type=X-GNOME-Metatheme
Comment=openSUSE téma

[X-GNOME-Metatheme]
GtkTheme=Sonar
MetacityTheme=Sonar
IconTheme=Sonar
GtkColorScheme=fg_color:#202020,bg_color:#D5DAD5,base_color:#fff,text_color:#3A3A3A,selected_bg_color:#5E7F3E,selected_fg_color:#fff,tooltip_bg_color:#F5F5B5,tooltip_fg_color:#000,menu_fg_color:#f6f6f6,menu_bg_color:#303030
CursorTheme=mate
CursorSize=24
NotificationTheme=standard
