#!/bin/sh -eux

export SHELL=/bin/bash
export LDFLAGS="-Wl,-rpath,/usr/lib/firefox/ -Wl,--no-keep-memory"

cd "$UB_OBJECTDIR"
mkdir -p js/src/.deps

# az UB_CONFIGURE_DIR="$UB_COMPILEDIR" forma nem jó, linker hiba lesz belőle
"$UB_COMPILEDIR"/configure \
	--prefix=/usr \
	--enable-application=browser \
	--enable-official-branding \
	--without-system-jpeg \
	--with-system-zlib \
	--with-pthreads \
	--with-system-nss \
	--with-system-nspr \
	--enable-system-cairo \
	--enable-system-sqlite \
	--enable-gio \
	--enable-pango \
	--enable-svg \
	--enable-canvas \
	--enable-xinerama \
	--enable-startup-notification \
	--enable-libxul \
	--disable-gconf \
	--disable-gnomeui \
	--disable-gnomevfs \
	--disable-installer \
	--disable-updater \
	--disable-crashreporter \
	--disable-tests \
	--disable-mochitest \
	--enable-default-toolkit=cairo-gtk2 \
	--disable-necko-wifi

ub_make

