#!/bin/sh -eux

cd "$UB_OBJECTDIR"

# 26.0 baromsága
cp "$UB_OBJECTDIR"/config/makefiles/xpidl/Makefile "$UB_OBJECTDIR"/config/makefiles/xpidl/Makefile.in

ub_install

cp "$UB_INSTALLDIR"/usr/lib/firefox/browser/icons/mozicon128.png "$UB_INSTALLDIR"/usr/share/pixmaps/firefox.png

rm -f "$UB_INSTALLDIR"/usr/lib/firefox/firefox
rm -f "$UB_INSTALLDIR"/usr/bin/firefox
ln -s /usr/lib/firefox/firefox "$UB_INSTALLDIR"/usr/bin/firefox
ln -s firefox "$UB_INSTALLDIR"/usr/lib/firefox-"$UB_VERSION"
ln -s firefox-"$UB_VERSION" "$UB_INSTALLDIR"/usr/include/firefox
ln -s firefox-"$UB_VERSION" "$UB_INSTALLDIR"/usr/share/idl/firefox

mkdir -p "$UB_INSTALLDIR"/usr/lib/firefox/browser/extensions/langpack-hu@firefox.mozilla.org
cp -aR "$UB_COMPILEDIR"/langpack-hu/. "$UB_INSTALLDIR"/usr/lib/firefox/browser/extensions/langpack-hu@firefox.mozilla.org/
