#!/bin/sh -eux

for d in $(printf 'f:\n\t@echo $(BOOTSTRAP_TARGETS)\ninclude bootstrap.mk\n' | make -f - f) ; do
	[[ -e ${d} ]] && continue
	pushd ${d/%configure/.} >/dev/null
	AT_NOELIBTOOLIZE="yes" AT_TOPLEVEL_EAUTORECONF="yes" \
	autoreconf -vif
	popd >/dev/null
done

export JAVA_EXE=/usr/lib/java/jre/bin/java
export ac_cv_path_LATEX=no
export ac_cv_lib_avcodec_ff_vdpau_vc1_decode_picture=yes

ub_compile \
	--enable-libbluray \
	--enable-pulse \
	--enable-sdl \
	--enable-gl \
	--disable-hal \
	--enable-udev \
	--enable-libusb \
	--enable-vaapi \
	--enable-vdpau \
	--disable-debug \
	--enable-xrandr \
	--enable-texturepacker \
	--enable-external-ffmpeg \
	--enable-external-libraries
