#!/bin/sh -eux

export LINGUAS="`ls po/*.po | sed 's:po/\(.*\)\.po$:\1:'`"
ub_compile \
	--enable-usermenu \
	--with-nlsdir=/usr/share/locale \
	--with-pixmapdir=/usr/share/pixmaps \
	--with-x

cd windowmaker-extra

ub_compile
