#!/bin/sh -eux

export LDFLAGS+="-Wl,-rpath,/usr/lib/chromium/ -Wl,--no-keep-memory"

build/gyp_chromium -f make build/all.gyp --no-parallel --depth=. \
	-Dtarget_arch=ia32 \
	-Dpython_ver="2.6" \
	-Dno_strict_aliasing=1 \
	-Dwerror= \
	-Ddisable_sse2=1 \
	-Dno_gc_sections=1 \
	-Drelease_optimize=2 \
	-Dlinux_sandbox_path=/usr/lib/chromium/chrome_sandbox \
	-Dfastbuild=1 \
	-Dlinux_strip_binary=1 \
	-Dlinux_use_gold_binary=1 \
	-Dlinux_use_gold_flags=1 \
	-Dffmpeg_branding=Chrome \
	-Dtoolkit_wiews=0 \
	-Dtoolkit_uses_gtk=1 \
	-Duse_system_ffmpeg=0 \
	-Duse_system_libjpeg=1 \
	-Duse_system_libxml=1 \
	-Duse_system_libxslt=1 \
	-Duse_system_ssl=0 \
	-Duse_system_sqlite=0 \
	-Duse_system_yasm=1 \
	-Duse_gnome_keyring=0 \
	-Duse_gconf=0 \
	-Duse_gio=1 \
	-Ddisable_nacl=1 \
	-Ddisable_pnacl=1 \
	-Denable_google_now=0 \
	-Dcomponent="shared_library"

make -j2 chrome chrome_sandbox BUILDTYPE=Release

