#!/bin/sh -eux

# ninja.
# a make használata már nem támogatott, nem is engedi azzal fordítani

unzip ninja.zip
cd ninja-1.4.0
./bootstrap.py --verbose
cd ..
rm -f ninja.zip

# ok, chromium

# Re-configure bundled ffmpeg. See bug #491378 for example reasons.
echo "Configuring bundled ffmpeg..."
pushd third_party/ffmpeg > /dev/null
chromium/scripts/build_ffmpeg.py linux ia32 --config-only
chromium/scripts/copy_config.sh
popd > /dev/null

export LDFLAGS+="-Wl,-rpath,/usr/lib/chromium/ -Wl,--no-keep-memory"
	
build/gyp_chromium -f ninja build/all.gyp --debug --no-parallel --depth=. \
	-Dhost_arch=ia32 \
	-Dtarget_arch=ia32 \
	-Dbuildtype=Official \
	-Dpython_ver="2.6" \
	-Dwerror= \
	-Ddisable_sse2=1 \
	-Dno_gc_sections=1 \
	-Drelease_optimize=2 \
	-Dfastbuild=1 \
	-Dlinux_strip_binary=1 \
	-Dlinux_use_bundled_gold=0 \
	-Dlinux_use_bundled_binutils=0 \
	-Dlinux_use_gold_flags=0 \
	-Dffmpeg_branding=Chrome \
	-Dtoolkit_wiews=0 \
	-Dtoolkit_uses_gtk=1 \
	-Duse_system_ffmpeg=0 \
	-Duse_system_libjpeg=1 \
	-Duse_system_libxml=1 \
	-Duse_system_libxslt=1 \
	-Duse_system_sqlite=0 \
	-Duse_system_yasm=1 \
	-Duse_gnome_keyring=0 \
	-Duse_gconf=0 \
	-Duse_gio=1 \
	-Ddisable_nacl=1 \
	-Ddisable_pnacl=1 \
	-Denable_google_now=0 \
	-Dcomponent="shared_library"

ninja-1.4.0/ninja -C out/Release chrome chrome_sandbox

