#!/bin/sh -eux
ub_install
valtozodir=$UB_INSTALLDIR/var/games/pinball
touch $valtozodir/{professor,tux}/highscores
chown root:users $valtozodir/{professor,tux} $valtozodir/{professor,tux}/highscores
chmod 664 $valtozodir/{professor,tux}/highscores
mv pinball.desktop $UB_INSTALLDIR/usr/share/applications/
