#!/bin/sh -eux

ub_compile \
	--with-udev-prefix=/ \
	--enable-udev_sync \
	--enable-udev_rules \
	--enable-fsadm \
	--enable-cmdlib \
	--enable-dmeventd \
	--libdir=/lib \
	--sbindir=/sbin \
	--with-clvmd=all \
	--enable-pkgconfig
