diff -Naur speech-dispatcher-0.6.7-orig/src/python/Makefile.in speech-dispatcher-0.6.7/src/python/Makefile.in
--- speech-dispatcher-0.6.7-orig/src/python/Makefile.in	2008-07-14 14:59:13.000000000 +0200
+++ speech-dispatcher-0.6.7/src/python/Makefile.in	2009-08-11 13:30:05.000000000 +0200
@@ -13,11 +13,11 @@
 
 install:
 	if test -x /usr/bin/python; then \
-		./setup.py install --prefix=${prefix}; \
+		./setup.py install --prefix=${DESTDIR}${prefix}; \
 	else \
 		echo "Python not found, not installing speechd module nor spd-conf"; \
 	fi
-	cp speechd_config/test.wav @snddatadir@
+	cp speechd_config/test.wav ${DESTDIR}@snddatadir@
 
 uninstall:
 	rm -f @snddatadir@/test.wav
