#!/bin/sh -eux

ub_install

rm "$UB_INSTALLDIR"/usr/share/desktop-directories/Development.directory
rm "$UB_INSTALLDIR"/usr/share/desktop-directories/Graphics.directory
rm "$UB_INSTALLDIR"/usr/share/desktop-directories/Settings.directory
