#!/bin/sh -eux

sed -i "/<glib\//d" src/*
./autogen.sh \
	--prefix=/usr \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--mandir=/usr/share/man \
	--infodir=/usr/share/info \
	--enable-shared \
	--build=i686-uhu-linux \
	--host=i686-uhu-linux \
	--disable-static \
	--with-logo-format=image \
	--disable-integration-wizard \
	--disable-deprecated

	
make CFLAGS="-O2 -march=i686 -mtune=generic"  all
