#!/bin/sh -eux

ub_install

mv "$UB_INSTALLDIR"/usr/share/icons/hicolor/24x24/devices/{,xf}printer.png
mv "$UB_INSTALLDIR"/usr/share/icons/hicolor/48x48/devices/{,xf}printer.png
mv "$UB_INSTALLDIR"/usr/share/icons/hicolor/scalable/devices/{,xf}printer.svg
