#!/bin/sh -eux

export SHELL=/bin/bash

cd build/workspaces
./update-workspaces.sh \
      --with-system-enet \
      --bindir=/usr/bin \
      --libdir=/usr/lib/0ad \
      --datadir=/usr/share/0ad/data
cd gcc
ub_make
