#!/bin/sh -eux

mkdir -p "$UB_INSTALLDIR"/usr/share/lucidor
cp -a lucidor/. "$UB_INSTALLDIR"/usr/share/lucidor/
cp -a lucidor.sh "$UB_INSTALLDIR"/usr/share/lucidor/
cp -a man/lucidor.1 "$UB_INSTALLDIR"/usr/share/man/man1/
ln -s ../lucidor/chrome/icons/default/default32.png \
	"$UB_INSTALLDIR"/usr/share/pixmaps/lucidor.png
cp -a data/lucidor.desktop "$UB_INSTALLDIR"/usr/share/applications/
