#!/bin/sh -eux

ub_install

# remove ctags/etags, they are in the ctags package
rm "$UB_INSTALLDIR"/usr/bin/{ctags,etags}
rm "$UB_INSTALLDIR"/usr/share/man/man1/{ctags,etags}.1

cp -a etc/images/icons/hicolor/48x48/apps/emacs.png "$UB_INSTALLDIR"/usr/share/pixmaps/emacs.png
