#!/bin/sh

. /etc/init.d/common

DAEMON=/usr/sbin/sshd
PIDFILE="/var/run/sshd.pid"

function _init() {
	[ -f /etc/ssh/ssh_host_key ] || ssh-keygen -t rsa1 -f /etc/ssh/ssh_host_key -N "" >/dev/null 2>&1
	[ -f /etc/ssh/ssh_host_dsa_key ] || ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N "" >/dev/null 2>&1
	[ -f /etc/ssh/ssh_host_rsa_key ] || ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N "" >/dev/null 2>&1
}

startstop "$@"
