#!/bin/sh -eux

cd build
make DESTDIR="${UB_INSTALLDIR}/usr" install
 cp -d lib/*.so* "${UB_INSTALLDIR}/usr/lib"
   [ -e lib/libptlapack.a ] && cp lib/libptlapack.a "${UB_INSTALLDIR}/usr/lib"
rm -f ${UB_INSTALLDIR}/usr/lib/liblapack.so