#!/bin/sh -eux
#./configure\
#	--prefix=/usr \
#	--sysconfdir=/etc \
#	--datadir=/usr/share/games \
#	--localstatedir=/var \
#	--mandir=/usr/share/man \
#	--infodir=/usr/share/info \
#	--enable-shared \
#	--build=i586-uhu-linux \
#ub_make
# sed -i 's|-lpng12|-lpng|g' configure

sh ./autogen.sh
ub_compile
