#!/bin/sh -eux

ub_install
rm -Rf ${UB_INSTALLDIR}/usr/share/omf/apport
ln -s ${UB_INSTALLDIR}/usr/share/apport/apport-gtk ${UB_INSTALLDIR}/usr/bin
ln -s ${UB_INSTALLDIR}/usr/share/apport/apport-kde ${UB_INSTALLDIR}/usr/bin
