#!/bin/sh -eux

ub_install

ln -sf graphic-login "$UB_INSTALLDIR"/etc/pam.d/gdm

rm -f "$UB_INSTALLDIR"/etc/gdm/Init/Default
ln -s ../../X11/xdm/Xsetup "$UB_INSTALLDIR"/etc/gdm/Init/Default

rm -Rf "$UB_INSTALLDIR"/usr/share/pixmaps/faces
rm -f "$UB_INSTALLDIR"/usr/share/xsessions/gnome.desktop
