#!/bin/bash -eux

./configure \
	--disable-hardening \
	--disable-java \
	--disable-docs \
	--target-arch=x86 \
	--target-cpu=i686
	
source ./env.sh
kmk all

cd ./out/linux.x86/release/bin/src
ub_make \
	KERN_DIR="/usr/src/linux-`uname -r`"
