#!/bin/sh -eux

ub_install

# a binárisok ugyanazok, mint a libwnck csomagban
rm -Rf "$UB_INSTALLDIR"/usr/bin
# a locale is
rm -Rf "$UB_INSTALLDIR"/usr/locale
rm -Rf "$UB_INSTALLDIR"/usr/lib/girepository-1.0