#!/bin/sh -eux
mkdir vdr
cp -r /usr/src/vdr/* vdr/
rm -r vdr/PLUGINS/src
mkdir -p vdr/PLUGINS/src
cp -r rotorng vdr/PLUGINS/src/
cd vdr/PLUGINS/src/rotorng
#cd vdr
make clean
make CONFDIR=/var/vdr/config \
	LOCDIR=/usr/share/locale \
	MANDIR="$UB_INSTALLDIR"/usr/share/man \
	BINDIR=/usr/bin \
	VIDEODIR=/var/vdr/video \
	PLUGINLIBDIR=/usr/lib/vdr \
	DVBDIR=/usr/include/linux/dvb \
	VDRDIR=/usr/src/vdr \
 	LOCALEDIR="$UB_INSTALLDIR"/usr/share/locale
