#!/bin/sh -eux
cd vdr
make \
	MANDIR="$UB_INSTALLDIR"/usr/share/man \
	BINDIR="$UB_INSTALLDIR"/usr/bin \
	CONFDIR="$UB_INSTALLDIR"/var/vdr/config \
	LOCDIR="$UB_INSTALLDIR"/usr/share/locale \
	PLUGINLIBDIR="$UB_INSTALLDIR"/usr/lib/vdr \
	VIDEODIR="$UB_INSTALLDIR"/var/vdr/video install-plugins
make \
	MANDIR="$UB_INSTALLDIR"/usr/share/man \
	BINDIR="$UB_INSTALLDIR"/usr/bin \
	CONFDIR="$UB_INSTALLDIR"/var/vdr/config \
	LOCDIR="$UB_INSTALLDIR"/usr/share/locale \
	PLUGINLIBDIR="$UB_INSTALLDIR"/usr/lib/vdr \
	VIDEODIR="$UB_INSTALLDIR"/var/vdr/video install-i18n

mkdir -p $UB_INSTALLDIR/var/vdr/config/plugins/transponders
mkdir -p $UB_INSTALLDIR/var/vdr/config/themes
cp ../transponders/* $UB_INSTALLDIR/var/vdr/config/plugins/transponders/
cp PLUGINS/src/rotorng/themes/* $UB_INSTALLDIR/var/vdr/config/themes/