#!/bin/bash -eux

KVER="$(ls -1 /lib/modules|grep i386)"

#célkönyvtárak
cellibdir="$UB_INSTALLDIR"/usr/lib
xmoduldir="$cellibdir"/xorg/modules
desktopdir="$UB_INSTALLDIR"/usr/share/applications
mandir="$UB_INSTALLDIR"/usr/share/man/man1/
vendordir="$UB_INSTALLDIR"/etc/OpenCL/vendors
pixmapdir="$UB_INSTALLDIR"/usr/share/pixmaps/

#könyvtárgyártás
mkdir -p "$cellibdir"/nvidia \
	"$xmoduldir"/{drivers,extensions} \
	"$desktopdir" \
	"$mandir" \
	"$vendordir" \
	"$pixmapdir"

# binárisok
mv	nvidia-xconfig \
	nvidia-settings \
	nvidia-bug-report.sh \
	nvidia-smi \
	tls_test \
	tls_test_dso.so \
	"$UB_INSTALLDIR"/usr/bin/

# desktop
mv	nvidia-settings.desktop "$desktopdir"/
mv	nvidia-settings.png "$pixmapdir"/

# man
gunzip	*.1.gz
mv	*.1 "$mandir"/

# vendor
mv	nvidia.icd "$vendordir"/

# installált kernel modul a csomagba
mv	lib $UB_INSTALLDIR/

# biztonságba helyezés a régi módon
mv	libglx.so."$UB_VERSION" "$cellibdir"/nvidia/

#Áthelyezzük a nem a $cellibdir alá kerülő *.so-kat
mv	nvidia_drv.so "$xmoduldir"/drivers/
mv	tls "$cellibdir"

# remove conflicting vdpau lib
###Jó nekünk az!
#rm "libvdpau.so.$UB_VERSION"
#rm "libvdpau_trace.so.$UB_VERSION"

#### Error: Nincs meg ez a lib: libGL.so (igényli: /usr/lib/libnvidia-ifr.so.319.60)
# Az igényelt libGL.so szimlink ütközne a mesa-dev -el,
# a mesa-dev függés viszont felrántana egy rakás dev -et,
# ezért lemondunk az NvIFROpenGL library használatáról egyelőre
rm -f libnvidia-ifr.so."$UB_VERSION"

# minden áthelyezése a libekbe
mv *.so.* "$cellibdir"/

#linkgyártások
cd "$cellibdir"
ln -s libwfb.so xorg/modules/libnvidia-wfb.so."$UB_VERSION"
ln -s "libvdpau_nvidia.so.$UB_VERSION" libvdpau_nvidia.so
ln -s "libnvcuvid.so.$UB_VERSION" libnvcuvid.so.1
ln -s libnvcuvid.so.1 libnvcuvid.so
ln -s "libcuda.so.$UB_VERSION" libcuda.so

