#!/bin/sh -eux

for file in libnss3.so libnssutil3.so libssl3.so libsmime3.so libsoftokn3.{so,chk} libnssckbi.so libfreebl3.{so,chk} libnssdbm3.{so,chk}; do
	install -m 644 dist/*.OBJ/lib/"$file" "$UB_INSTALLDIR"/usr/lib
done
  
for file in libcrmf.a libnssb.a libnssckfw.a; do
	install -m 644 dist/*.OBJ/lib/"$file" "$UB_INSTALLDIR"/usr/lib
done
	
for file in certutil modutil pk12util signtool ssltap; do
	install -m 755 dist/*.OBJ/bin/"$file" "$UB_INSTALLDIR"/usr/bin
done
  
mkdir -p "$UB_INSTALLDIR"/usr/include/nss3
for file in dist/public/nss/*.h; do
	install -m 644 "$file" "$UB_INSTALLDIR"/usr/include/nss3
done


NSPR_VERSION=`pkg-config --modversion nspr`

# create nss.pc
mkdir -p "$UB_INSTALLDIR"/usr/lib/pkgconfig
cat nss.pc.in | sed -e "s,%libdir%,/usr/lib,g" \
					-e "s,%prefix%,/usr,g" \
					-e "s,%exec_prefix%,/usr,g" \
					-e "s,%includedir%,/usr/include/nss3,g" \
					-e "s,%NSPR_VERSION%,$NSPR_VERSION,g" \
					-e "s,%NSS_VERSION%,$UB_VERSION,g" > \
					"$UB_INSTALLDIR"/usr/lib/pkgconfig/nss.pc

NSS_VMAJOR=`cat lib/nss/nss.h | grep "#define.*NSS_VMAJOR" | awk '{print $3}'`
NSS_VMINOR=`cat lib/nss/nss.h | grep "#define.*NSS_VMINOR" | awk '{print $3}'`
NSS_VPATCH=`cat lib/nss/nss.h | grep "#define.*NSS_VPATCH" | awk '{print $3}'`

#create nss-config
mkdir -p "$UB_INSTALLDIR"/usr/bin
cat nss-config.in | sed -e "s,@libdir@,/usr/lib,g" \
                        -e "s,@prefix@,/usr,g" \
						-e "s,@exec_prefix@,/usr,g" \
						-e "s,@includedir@,/usr/include/nss3,g" \
						-e "s,@MOD_MAJOR_VERSION@,$NSS_VMAJOR,g" \
						-e "s,@MOD_MINOR_VERSION@,$NSS_VMINOR,g" \
						-e "s,@MOD_PATCH_VERSION@,$NSS_VPATCH,g" \
						> "$UB_INSTALLDIR"/usr/bin/nss-config
chmod 755 "$UB_INSTALLDIR"/usr/bin/nss-config
