#!/bin/sh -eux

ub_install

for theme in nuvola; do
	for i in 16x16 22x22 32x32 48x48 64x64 128x128; do
		mkdir -p "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories

		ln -s /usr/share/icons/$theme/$i/categories/applications-other.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-applications.png
		ln -s /usr/share/icons/$theme/$i/categories/applications-development.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-development.png
		ln -s /usr/share/icons/$theme/$i/categories/applications-games.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-games.png
		ln -s /usr/share/icons/$theme/$i/categories/applications-graphics.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-gfx.png
		ln -s /usr/share/icons/$theme/$i/categories/applications-internet.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/stock-panel-internet.png
		ln -s /usr/share/icons/$theme/$i/categories/applications-multimedia.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-media.png
		ln -s /usr/share/icons/$theme/$i/mimetypes/document.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-documentation.png
		ln -s /usr/share/icons/$theme/$i/categories/applications-education.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/package_edutainment.png
		ln -s /usr/share/icons/$theme/$i/actions/configure.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-configuration.png
		ln -s /usr/share/icons/$theme/$i/apps/accessories-text-editor.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-accessories.png
		ln -s /usr/share/icons/$theme/$i/devices/computer.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-computer.png
		ln -s /usr/share/icons/$theme/$i/apps/system-file-manager.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-filemanager.png
		ln -s /usr/share/icons/$theme/$i/apps/knotes.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-notepad.png
		ln -s /usr/share/icons/$theme/$i/categories/preferences-system-network.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-network.png
		ln -s /usr/share/icons/$theme/$i/devices/modem.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-network-firewall.png
		ln -s /usr/share/icons/$theme/$i/devices/network-wired.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-network-system.png
		ln -s /usr/share/icons/$theme/$i/devices/printer.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/stock-print.png
		ln -s /usr/share/icons/$theme/$i/mimetypes/text-html.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-html.png
		ln -s /usr/share/icons/$theme/$i/actions/view-preview.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-monitor.png
		ln -s /usr/share/icons/$theme/$i/categories/applications-toys.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-launcher.png
		ln -s /usr/share/icons/$theme/$i/apps/accessories-calculator.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-calculator.png
		ln -s /usr/share/icons/$theme/$i/apps/date.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-date.png
		ln -s /usr/share/icons/$theme/$i/apps/date.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-datetime.png
		ln -s /usr/share/icons/$theme/$i/categories/applications-office.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-office.png
		ln -s /usr/share/icons/$theme/$i/apps/accessories-dictionary.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/stock-book.png
		ln -s /usr/share/icons/$theme/$i/categories/applications-office.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-office-wordprocessor.png
		ln -s /usr/share/icons/$theme/$i/apps/kpresenter.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-office-presentation.png
		ln -s /usr/share/icons/$theme/$i/mimetypes/x-office-spreadsheet.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-office-spreadsheet.png
		ln -s /usr/share/icons/$theme/$i/apps/utilities-terminal.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-terminal.png
		ln -s /usr/share/icons/$theme/$i/apps/preferences-desktop-locale.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/stock-convert.png
		ln -s /usr/share/icons/$theme/$i/apps/laptop_pcmcia.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/file-devel.png
		ln -s /usr/share/icons/$theme/$i/apps/ksnapshot.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/stock-panel-screenshot.png
		ln -s /usr/share/icons/$theme/$i/apps/knewsticker.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/news.png
		ln -s /usr/share/icons/$theme/$i/apps/browser.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-web-browser.png
		ln -s /usr/share/icons/$theme/$i/apps/download_manager.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-update.png
		ln -s /usr/share/icons/$theme/$i/apps/internet-mail.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-email.png
		ln -s /usr/share/icons/$theme/$i/apps/chat.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-instantmessage.png
		ln -s /usr/share/icons/$theme/$i/categories/applications-games-arcade.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/package_games_arcade.png
		ln -s /usr/share/icons/$theme/$i/actions/roll.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/package_games_board.png
		ln -s /usr/share/icons/$theme/$i/apps/amor.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/package_games_card.png
		ln -s /usr/share/icons/$theme/$i/categories/applications-games-strategy.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/package_games_strategy.png
		ln -s /usr/share/icons/$theme/$i/actions/edit-bomb.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/package_games.png
		ln -s /usr/share/icons/$theme/$i/categories/applications-toys.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/package_toys.png
		ln -s /usr/share/icons/$theme/$i/devices/media-optical.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/cd.png
		ln -s /usr/share/icons/$theme/$i/apps/kmix.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-mixer.png
		ln -s /usr/share/icons/$theme/$i/apps/preferences-desktop-sound.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-sound.png
		ln -s /usr/share/icons/$theme/$i/apps/mplayer.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/emblem-video.png
		ln -s /usr/share/icons/$theme/$i/devices/video-television.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-television.png
		ln -s /usr/share/icons/$theme/$i/categories/applications-education-language.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/edu_languages.png
		ln -s /usr/share/icons/$theme/$i/categories/applications-education-mathematics.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/edu_mathematics.png
		ln -s /usr/share/icons/$theme/$i/categories/applications-other.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/edu_miscellaneous.png
		ln -s /usr/share/icons/$theme/$i/categories/applications-science.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/edu_science.png
		ln -s /usr/share/icons/$theme/$i/apps/bookcase.png "$UB_INSTALLDIR"/usr/share/icons/$theme/$i/categories/icon-logbook.png
	done
done
