#!/bin/sh -eux

ub_install
# webkitgtk-dev csomaggal ütköző dokumentáció átmozgatása
mv $UB_INSTALLDIR/usr/share/gtk-doc ./webkitgtk3
mkdir -p $UB_INSTALLDIR/usr/share/gtk-doc
mv webkitgtk3 $UB_INSTALLDIR/usr/share/gtk-doc/
