#!/bin/sh

. /etc/init.d/common

DAEMON="/usr/sbin/mysqld"
PIDFILE="/var/run/mysqld/mysqld.pid"
DAEMONARGS=(--pid-file="$PIDFILE" --log-error=/var/lib/mysql/err.log)

export _MYSQL_FORK=1
cd /var/lib/mysql
startstop "$@"
