#!/bin/sh -eux

ub_install

mkdir -p $UB_INSTALLDIR/var/vdr/config/themes
cd $UB_SRCDIR/sources
cp 'PearlHD(native)-Accessibility.theme' $UB_INSTALLDIR/var/vdr/config/themes/PearlHD-Accessibility.theme
cp 'PearlHD(native)-Beige.theme' $UB_INSTALLDIR/var/vdr/config/themes/PearlHD-Beige.theme
cp 'PearlHD(native)-Blue.theme' $UB_INSTALLDIR/var/vdr/config/themes/PearlHD-Blue.theme
cp 'PearlHD(native)-White.theme' $UB_INSTALLDIR/var/vdr/config/themes/PearlHD-White.theme

